theme: jekyll-theme-chirpy

baseurl: ''

lang: en

timezone: America/Los_Angeles

title: emadyounis.com

description: Emad Younis

url: 'https://emadyounis.com'

github:
  username: younise

twitter:
  username: emad_younis

linkedin:
  username: eyounis

social:
  name: Emad Younis
  email: example@domain.com
  links:
    - https://twitter.com/emad_younis
    - https://github.com/younise
    - https://www.linkedin.com/in/eyounis/

google_site_verification:               # fill in to your verification string

google_analytics:
  id:                 # fill in your Google Analytics ID
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

theme_mode: dark

avatar: '/assets/img/emad.png'

toc: true

pwa:
  enabled: true   # the option for PWA feature

paginate: 5

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/